[project]
authors = [{ name = "Weiliang Li", email = "to.be.impressive@gmail.com" }]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Environment :: Web Environment",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: Free Threading :: 2 - Beta",
]
dependencies = ["typing_extensions>=4; python_version < '3.11'"]
description = "The revamped and modernized drop-in replacement for asgiref"
license = "BSD-3-Clause"
name = "asgire"
readme = "README.md"
requires-python = ">=3.10"
version = "3.12.2"

[project.urls]
Changelog = "https://github.com/kigawas/asgire/blob/main/CHANGELOG.md"
Homepage = "https://github.com/kigawas/asgire"
Issues = "https://github.com/kigawas/asgire/issues"
Repository = "https://github.com/kigawas/asgire"

[dependency-groups]
dev = [
  "pytest>=9.1.1",
  "pytest-asyncio>=1.4.0",
  "pytest-cov>=7.1.0",
  "ruff>=0.16.0",
  "ty>=0.0.63",
]

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core>=3.2"]

[tool.flit.module]
name = "asgiref"

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
asyncio_mode = "strict"
testpaths = ["tests"]

[tool.coverage.run]
omit = ["asgiref/typing.py"]

[tool.ty.src]
exclude = ["tests/"]

[tool.ruff]
line-length = 119
extend-exclude = ["README.md"]

[tool.ruff.lint]
select = ["E", "F", "I", "W"]
